baseURL = "http://2020.computational-humanities-research/"
languageCode = "en-us"
title = "Computational Humanities Research"
theme = "chr"
publishDir = "docs"

[params]
  customCSS = ["css/custom.css"]

[menu]

  [[menu.main]]
    identifier = "cfp"
    name = "Workshop"
    url = "/cfp/"
    weight = -1100

  [[menu.main]]
   identifier = "papers"
   name = "Acccepted papers"
   url = "/papers/"
   weight = -1200

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = -210

  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/community/"
    weight = -1000

[markup.goldmark.renderer]
unsafe = true